import type { Tour } from '../types'

/** The hospital-admin / super-admin overview - broader, covers the back office. */
export const adminWorkflow: Tour = {
  id: 'admin-workflow',
  title: 'Running the hospital',
  section: 'Core workflow',
  summary: 'Staff, master data, money, and how every module feeds the next.',
  steps: [
    {
      id: 'overview',
      route: '/dashboard',
      target: '[data-tour="dashboard-widgets"]',
      title: 'The whole hospital, one screen',
      body: 'As an admin your dashboard rolls up bed occupancy, today\'s appointments by status, money collected versus billed, and outstanding claims.',
      placement: 'top',
    },
    {
      id: 'how-it-connects',
      route: '/dashboard',
      target: '[data-tour="dashboard-greeting"]',
      title: 'How the modules connect',
      body: 'Patient -> appointment -> check-in -> consultation -> diagnosis -> prescription or lab request -> the invoice builds automatically -> payment or an HMO claim -> follow-up. Each module hands off to the next with no re-keying.',
      placement: 'bottom',
    },
    {
      id: 'hr',
      route: '/hr',
      target: '[data-tour="hr-main"]',
      title: 'Staff',
      body: 'Add users and set their role - the role decides what each person can see and do. Assign departments, set an initial password, and deactivate anyone who leaves.',
      placement: 'top',
      permission: 'staff:manage',
    },
    {
      id: 'admin',
      route: '/admin',
      target: '[data-tour="admin-tabs"]',
      title: 'Master data',
      body: 'Services and their prices, departments, and insurance providers. Billing, scheduling and claims all draw on what you set here, so keep it current.',
      placement: 'bottom',
      permission: 'admin:settings',
    },
    {
      id: 'settings',
      route: '/settings',
      target: '[data-tour="settings-sections"]',
      title: 'Hospital settings',
      body: 'Your hospital\'s name, logo and brand colour, plus the invoice and receipt number prefixes that appear on every printed document.',
      placement: 'top',
      permission: 'admin:settings',
    },
    {
      id: 'billing',
      route: '/billing',
      target: '[data-tour="billing-list"]',
      title: 'The money in',
      body: 'Every invoice and payment across the hospital. Reverse a payment, cancel an invoice, or build one by hand from the price list.',
      placement: 'top',
      permission: 'billing:manage',
    },
    {
      id: 'claims',
      route: '/claims',
      target: '[data-tour="claims-main"]',
      title: 'HMO claims',
      body: 'Generate claims from HMO visit invoices, batch them per provider, export the schedule, then record remittances - the payments post back onto the right invoices automatically.',
      placement: 'top',
      permission: 'claims:manage',
    },
    {
      id: 'reports',
      route: '/reports',
      target: '[data-tour="reports-range"]',
      title: 'Reports',
      body: 'Collections, revenue by department and doctor, patient trends, and a filterable payment ledger - all exportable as CSV for any date range.',
      placement: 'bottom',
      permission: 'reports:view',
    },
    {
      id: 'help',
      route: '/dashboard',
      target: '[data-tour="nav-support"]',
      title: 'Onboarding your team',
      body: 'Each new staff member gets their own role-specific tour on first login, and can replay it any time from Support. Point new hires there.',
      placement: 'right',
    },
  ],
}
